// examples/svelte/AgeCheck.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { registerAgeCheckElement } from "@dlbr/eid-age-check";

  let widget: HTMLElement;
  let accessGranted = false;

  onMount(() => {
    registerAgeCheckElement();
    const onVerified = () => {
      accessGranted = true;
    };
    widget.addEventListener("age-verified", onVerified);
    return () => widget.removeEventListener("age-verified", onVerified);
  });
</script>

<dlbr-age-check bind:this={widget} endpoint="/api/age-check"></dlbr-age-check>

{#if accessGranted}
  <p>Age verified. Continue with your own access rules.</p>
{/if}

// examples/vue/AgeCheck.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import { registerAgeCheckElement } from "@dlbr/eid-age-check";

const widget = ref<HTMLElement | null>(null);
const accessGranted = ref(false);

function onVerified() {
  accessGranted.value = true;
}

onMounted(() => {
  registerAgeCheckElement();
  widget.value?.addEventListener("age-verified", onVerified);
});

onBeforeUnmount(() => {
  widget.value?.removeEventListener("age-verified", onVerified);
});
</script>

<template>
  <dlbr-age-check ref="widget" endpoint="/api/age-check" />
  <section v-if="accessGranted">Age verified. Continue with your own access rules.</section>
</template>
